import { Ionicons } from '@expo/vector-icons';
import { router, useFocusEffect, useLocalSearchParams } from 'expo-router';
import { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, FlatList, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { AbstractHero, FateDropBackground, StatusBadge } from '@/components/fatedrop-ui';
import { API_BASE_URL } from '@/constants/api';
import { FateDropColors } from '@/constants/theme';
import { openTrackedRetailerLink } from '@/services/outbound-links';
import { LocalWishlistRepository } from '@/services/wishlist';
import type { ProductCondition } from '@/types/domain';

interface Inventory{id:string;title:string;category:string;condition:string;priceGbp?:number;stockStatus:string;productUrl?:string;}interface Vendor{id:string;retailerId:string;retailerName:string;stallIdentifier?:string;isDemo:boolean;inventory:Inventory[];}type Row=Inventory&{vendor:Vendor};
const wishlist=new LocalWishlistRepository();

export default function EventVendorsScreen(){
  const params=useLocalSearchParams<{eventId?:string}>(),eventId=params.eventId||'card-con-iv-2026',[query,setQuery]=useState(''),[vendors,setVendors]=useState<Vendor[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[saved,setSaved]=useState<string[]>([]);
  useFocusEffect(useCallback(()=>{void wishlist.list().then(items=>setSaved(items.map(item=>item.targetId)))},[]));
  useEffect(()=>{const timer=setTimeout(()=>{setLoading(true);setError('');void fetch(`${API_BASE_URL}/api/events/${encodeURIComponent(eventId)}/vendors?q=${encodeURIComponent(query)}`).then(response=>{if(!response.ok)throw new Error();return response.json()}).then(data=>setVendors(data.vendors||[])).catch(()=>setError('Vendor inventory could not be loaded.')).finally(()=>setLoading(false));},300);return()=>clearTimeout(timer)},[eventId,query]);
  const items=vendors.flatMap(vendor=>vendor.inventory.map(item=>({...item,vendor})));
  const toggle=async(row:Row)=>{const targetId=`event:${eventId}:${row.id}`,id=`product:${targetId}`;if(saved.includes(targetId)){await wishlist.remove(id);setSaved(current=>current.filter(value=>value!==targetId));}else{await wishlist.save({id,targetType:'PRODUCT',targetId,label:row.title,condition:row.condition as ProductCondition,alertsEnabled:false,createdAt:new Date().toISOString()});setSaved(current=>[...current,targetId]);}};
  const header=<><Pressable onPress={()=>router.back()} style={styles.back}><Ionicons name="arrow-back" size={20} color={FateDropColors.text}/><Text style={styles.backText}>Back</Text></Pressable><AbstractHero eyebrow="Event Vendor Mode" title="Find it at the show." subtitle="Search participating vendor inventories, prices, conditions and stall locations for this event." icon="search"/><View style={styles.demo}><StatusBadge label="Demo inventory" color={FateDropColors.amber}/><Text style={styles.demoText}>Fictional vendors and stock for product demonstration. This is not live availability.</Text></View><View style={styles.search}><Ionicons name="search" size={18} color={FateDropColors.muted}/><TextInput value={query} onChangeText={setQuery} placeholder="Search cards or sealed products" placeholderTextColor={FateDropColors.muted} style={styles.input}/></View></>;
  return <SafeAreaView style={styles.safe}><FateDropBackground/><FlatList data={items} keyExtractor={item=>item.id} contentContainerStyle={styles.content} ListHeaderComponent={header} ListEmptyComponent={loading?<ActivityIndicator color={FateDropColors.violetLight} style={styles.state}/>:<Text style={styles.state}>{error||'No vendor stock matches this search.'}</Text>} renderItem={({item})=><InventoryCard row={item} saved={saved.includes(`event:${eventId}:${item.id}`)} onToggle={()=>void toggle(item)}/>} /></SafeAreaView>;
}
function InventoryCard({row,saved,onToggle}:{row:Row;saved:boolean;onToggle:()=>void}){return <View style={styles.card}><View style={styles.cardTop}><View style={{flex:1}}><Text style={styles.title}>{row.title}</Text><Text style={styles.vendor}>{row.vendor.retailerName} · {row.vendor.stallIdentifier||'Stall TBC'}</Text></View><Text style={styles.price}>{row.priceGbp===undefined?'Price TBC':`£${row.priceGbp.toFixed(2)}`}</Text><Pressable accessibilityLabel={saved?'Remove event item from wishlist':'Save event item'} onPress={onToggle}><Ionicons name={saved?'bookmark':'bookmark-outline'} size={20} color={FateDropColors.violetLight}/></Pressable></View><View style={styles.meta}><StatusBadge label={row.condition.replaceAll('_',' ')} color={FateDropColors.cyan}/><StatusBadge label={row.stockStatus.replaceAll('_',' ')} color={FateDropColors.mint}/></View><View style={styles.actions}><Pressable onPress={()=>router.push({pathname:'/retailers/[id]',params:{id:row.vendor.retailerId}})} style={styles.secondary}><Text style={styles.secondaryText}>Vendor profile</Text></Pressable>{row.productUrl?<Pressable onPress={()=>void openTrackedRetailerLink({destinationUrl:row.productUrl!,retailerId:row.vendor.retailerId,offerId:row.id,placement:'event-vendor'})} style={styles.primary}><Text style={styles.primaryText}>Open demo item</Text><Ionicons name="open-outline" size={14} color={FateDropColors.text}/></Pressable>:null}</View></View>}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:FateDropColors.background},content:{paddingHorizontal:20,paddingBottom:80},back:{flexDirection:'row',gap:8,alignItems:'center',paddingVertical:12},backText:{color:FateDropColors.text,fontWeight:'800'},demo:{padding:12,borderRadius:15,backgroundColor:`${FateDropColors.amber}10`,borderWidth:1,borderColor:`${FateDropColors.amber}33`,marginBottom:12},demoText:{color:FateDropColors.secondary,fontSize:10,lineHeight:16,marginTop:7},search:{flexDirection:'row',alignItems:'center',gap:9,padding:12,borderRadius:16,backgroundColor:FateDropColors.glass,borderWidth:1,borderColor:FateDropColors.border,marginBottom:14},input:{flex:1,color:FateDropColors.text},state:{color:FateDropColors.muted,textAlign:'center',margin:35},card:{padding:15,borderRadius:18,backgroundColor:FateDropColors.glass,borderWidth:1,borderColor:FateDropColors.border,marginBottom:9},cardTop:{flexDirection:'row',alignItems:'flex-start',gap:10},title:{color:FateDropColors.text,fontWeight:'900'},vendor:{color:FateDropColors.secondary,fontSize:10,marginTop:5},meta:{flexDirection:'row',gap:6,marginTop:9},price:{color:FateDropColors.mint,fontWeight:'900',fontSize:16},actions:{flexDirection:'row',gap:8,marginTop:12},primary:{flex:1,flexDirection:'row',gap:6,alignItems:'center',justifyContent:'center',padding:10,borderRadius:12,backgroundColor:FateDropColors.violet},primaryText:{color:FateDropColors.text,fontWeight:'800',fontSize:10},secondary:{flex:1,alignItems:'center',padding:10,borderRadius:12,borderWidth:1,borderColor:FateDropColors.border},secondaryText:{color:FateDropColors.text,fontWeight:'800',fontSize:10}});
