import { Ionicons } from '@expo/vector-icons';
import { router, useLocalSearchParams } from 'expo-router';
import { useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, FlatList, Linking, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { AbstractHero, FateDropBackground, StatusBadge } from '@/components/fatedrop-ui';
import { FateDropColors } from '@/constants/theme';
import { isSafeExternalUrl } from '@/lib/encounters';
import { loadEncounterVendors } from '@/services/encounters';
import type { EncounterInventoryItem, EncounterVendor } from '@/types/encounter';

type Row=EncounterInventoryItem&{vendor:EncounterVendor};
const money=(pence?:number|null)=>pence==null?'Price TBC':`£${(pence/100).toFixed(2)}`;

export default function EventVendorsScreen(){
  const params=useLocalSearchParams<{eventId?:string}>(),eventId=Array.isArray(params.eventId)?params.eventId[0]:params.eventId,[query,setQuery]=useState(''),[vendors,setVendors]=useState<EncounterVendor[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
  useEffect(()=>{let active=true;if(!eventId){setError('No encounter selected.');setLoading(false);return()=>{active=false};}setLoading(true);setError('');void loadEncounterVendors(eventId).then(data=>{if(active)setVendors(data)}).catch(()=>{if(active)setError('Confirmed event vendors could not be loaded.')}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[eventId]);
  const needle=query.trim().toLowerCase();
  const items=useMemo(()=>vendors.flatMap(vendor=>(vendor.inventory||[]).filter(item=>!needle||`${item.title} ${vendor.name} ${vendor.stallLabel||''}`.toLowerCase().includes(needle)).map(item=>({...item,vendor}))),[needle,vendors]);
  const header=<><Pressable onPress={()=>router.back()} style={styles.back}><Ionicons name="arrow-back" size={20} color={FateDropColors.text}/><Text style={styles.backText}>Back</Text></Pressable><AbstractHero eyebrow="Event Vendor Mode" title="Find it at the show." subtitle="Confirmed participating vendors, stall locations and evidence-backed event inventory for this encounter." icon="search"/><View style={styles.truth}><StatusBadge label="Evidence only" color={FateDropColors.mint}/><Text style={styles.truthText}>Stock appears here only when a vendor or FateDrop event-inventory source has explicitly reported it. It expires rather than becoming permanent availability.</Text></View><View style={styles.search}><Ionicons name="search" size={18} color={FateDropColors.muted}/><TextInput value={query} onChangeText={setQuery} placeholder="Search vendor event stock" placeholderTextColor={FateDropColors.muted} style={styles.input}/></View>{vendors.length?<Text style={styles.vendorCount}>{vendors.length} confirmed/listed vendor{vendors.length===1?'':'s'} · {items.length} active inventory item{items.length===1?'':'s'}</Text>:null}</>;
  return <SafeAreaView style={styles.safe}><FateDropBackground/><FlatList data={items} keyExtractor={item=>item.id} contentContainerStyle={styles.content} ListHeaderComponent={header} ListEmptyComponent={loading?<ActivityIndicator color={FateDropColors.violetLight} style={styles.state}/>:<Text style={styles.state}>{error||'No active event inventory is published for this encounter yet.'}</Text>} renderItem={({item})=><InventoryCard row={item}/>} /></SafeAreaView>;
}
function InventoryCard({row}:{row:Row}){
  const location=[row.vendor.zoneLabel,row.vendor.stallLabel].filter(Boolean).join(' · ')||'Stall TBC';
  const evidence=row.evidenceScope==='fatedrop_event_inventory'?'FateDrop event inventory':'Vendor reported';
  const openVendor=()=>{if(row.vendor.retailerId){router.push({pathname:'/retailers/[id]',params:{id:row.vendor.retailerId}});return;}if(row.vendor.websiteUrl&&isSafeExternalUrl(row.vendor.websiteUrl))void Linking.openURL(row.vendor.websiteUrl);};
  return <View style={styles.card}><View style={styles.cardTop}><View style={styles.copy}><Text style={styles.title}>{row.title}</Text><Text style={styles.vendor}>{row.vendor.name} · {location}</Text></View><Text style={styles.price}>{money(row.pricePence)}</Text></View><View style={styles.meta}><StatusBadge label={row.availability.replaceAll('_',' ')} color={row.availability==='sold_out'?FateDropColors.coral:FateDropColors.mint}/><StatusBadge label={evidence} color={FateDropColors.cyan}/>{row.quantity!=null?<StatusBadge label={`Qty ${row.quantity}`} color={FateDropColors.amber}/>:null}</View><Text style={styles.observed}>Observed {new Date(row.observedAt).toLocaleString('en-GB')}{row.expiresAt?` · expires ${new Date(row.expiresAt).toLocaleString('en-GB')}`:''}</Text>{row.vendor.retailerId||row.vendor.websiteUrl?<Pressable onPress={openVendor} style={styles.primary}><Text style={styles.primaryText}>{row.vendor.retailerId?'Vendor profile':'Vendor website'}</Text><Ionicons name="chevron-forward" size={14} color={FateDropColors.text}/></Pressable>:null}</View>;
}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:FateDropColors.background},content:{paddingHorizontal:20,paddingBottom:80},back:{flexDirection:'row',gap:8,alignItems:'center',paddingVertical:12},backText:{color:FateDropColors.text,fontWeight:'800'},truth:{padding:12,borderRadius:15,backgroundColor:`${FateDropColors.mint}08`,borderWidth:1,borderColor:`${FateDropColors.mint}30`,marginBottom:12},truthText:{color:FateDropColors.secondary,fontSize:10,lineHeight:16,marginTop:7},search:{flexDirection:'row',alignItems:'center',gap:9,padding:12,borderRadius:16,backgroundColor:FateDropColors.glass,borderWidth:1,borderColor:FateDropColors.border,marginBottom:10},input:{flex:1,color:FateDropColors.text},vendorCount:{color:FateDropColors.muted,fontSize:10,marginBottom:14},state:{color:FateDropColors.muted,textAlign:'center',margin:35},card:{padding:15,borderRadius:18,backgroundColor:FateDropColors.glass,borderWidth:1,borderColor:FateDropColors.border,marginBottom:9},cardTop:{flexDirection:'row',alignItems:'flex-start',gap:10},copy:{flex:1},title:{color:FateDropColors.text,fontWeight:'900'},vendor:{color:FateDropColors.secondary,fontSize:10,marginTop:5},meta:{flexDirection:'row',flexWrap:'wrap',gap:6,marginTop:9},price:{color:FateDropColors.mint,fontWeight:'900',fontSize:16},observed:{color:FateDropColors.muted,fontSize:9,lineHeight:14,marginTop:10},primary:{marginTop:12,flexDirection:'row',gap:6,alignItems:'center',justifyContent:'center',padding:10,borderRadius:12,backgroundColor:FateDropColors.violet},primaryText:{color:FateDropColors.text,fontWeight:'800',fontSize:10}});
