import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { useEffect, useMemo, useState } from 'react';
import { FlatList, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { AbstractHero, FateDropBackground, FilterChip, StatusBadge } from '@/components/fatedrop-ui';
import { API_BASE_URL } from '@/constants/api';
import { retailers } from '@/constants/retailers';
import { FateDropColors } from '@/constants/theme';
import { distanceMiles, ExpoLocationAdapter, geocodeEventLocation, type UserArea } from '@/services/location';

interface RadarEvent{id:string;name:string;kind?:'EVENT'|'SHOP';retailerId?:string;startDateTime?:string;venueName?:string;townCity?:string;postcode?:string;categories?:string[];organiserName?:string;latitude?:number;longitude?:number;distanceMiles?:number;}
type DateWindow='all'|'30'|'90';
const adapter=new ExpoLocationAdapter();
const outward=(postcode?:string)=>postcode?.replace(/\s+/g,'').slice(0,-3).toUpperCase();

export default function LocalRadarScreen(){
  const [events,setEvents]=useState<RadarEvent[]>([]),[area,setArea]=useState<UserArea>(),[postcode,setPostcode]=useState(''),[error,setError]=useState(''),[radius,setRadius]=useState(25),[dateWindow,setDateWindow]=useState<DateWindow>('90'),[eventType,setEventType]=useState('All types'),[organiser,setOrganiser]=useState('All organisers'),[locating,setLocating]=useState(false);
  useEffect(()=>{void fetch(`${API_BASE_URL}/api/calendar-events`).then(r=>r.json()).then(data=>setEvents(data.events||[])).catch(()=>setError('Nearby events could not be loaded.'))},[]);
  const device=async()=>{setError('');setLocating(true);try{const current=await adapter.requestCurrentArea();setArea(current);const located=await Promise.all(events.map(async event=>{if(!event.postcode)return event;try{const coordinates=await geocodeEventLocation(event.postcode);return coordinates?{...event,...coordinates,distanceMiles:distanceMiles(current as Required<Pick<UserArea,'latitude'|'longitude'>>,coordinates)}:event;}catch{return event;}}));setEvents(located);}catch(reason){setError(reason instanceof Error&&reason.message==='LOCATION_DENIED'?'Location permission was denied. Enter a postcode instead.':'Location could not be determined.')}finally{setLocating(false)}};
  const manual=async()=>{setError('');try{setArea(await adapter.fromPostcode(postcode))}catch{setError('Enter a valid UK postcode.')}};
  const shops=useMemo<RadarEvent[]>(()=>retailers.flatMap(retailer=>retailer.locations.filter(location=>location.latitude!==undefined&&location.longitude!==undefined).map(location=>({id:`shop:${location.id}`,name:retailer.name,kind:'SHOP' as const,retailerId:retailer.id,venueName:location.name,townCity:location.townCity,postcode:location.postcode,categories:['Card shop','Nearby stock'],organiserName:retailer.name,latitude:location.latitude,longitude:location.longitude,distanceMiles:area?.source==='DEVICE'&&area.latitude!==undefined&&area.longitude!==undefined?distanceMiles({latitude:area.latitude,longitude:area.longitude},{latitude:location.latitude!,longitude:location.longitude!}):undefined}))),[area]);
  const allItems=useMemo(()=>[...events.map(event=>({...event,kind:'EVENT' as const})),...shops],[events,shops]);
  const types=useMemo(()=>['All types',...new Set(allItems.flatMap(event=>event.categories||[]))],[allItems]);
  const organisers=useMemo(()=>['All organisers',...new Set(allItems.map(event=>event.organiserName).filter((value):value is string=>Boolean(value)))],[allItems]);
  const filtered=useMemo(()=>allItems.filter(item=>{if(item.kind==='EVENT'&&item.startDateTime){const start=Date.parse(item.startDateTime),days=(start-Date.now())/86400000;if(dateWindow!=='all'&&(days<0||days>Number(dateWindow)))return false;}if(eventType!=='All types'&&!item.categories?.includes(eventType))return false;if(organiser!=='All organisers'&&item.organiserName!==organiser)return false;if(area?.source==='DEVICE'&&item.distanceMiles!==undefined&&item.distanceMiles>radius)return false;if(area?.source==='POSTCODE'&&outward(item.postcode)!==outward(area.postcode))return false;return true;}),[allItems,area,dateWindow,eventType,organiser,radius]);
  const header=<><Pressable onPress={()=>router.back()} style={styles.back}><Ionicons name="arrow-back" size={20} color={FateDropColors.text}/><Text style={styles.backText}>Back</Text></Pressable><AbstractHero eyebrow="Local Radar" title="Find the action nearby." subtitle="Discover card shows, trade nights, tournaments and shops without publishing your precise location." icon="navigate"/><View style={styles.permission}><Text style={styles.permissionTitle}>Location is optional</Text><Text style={styles.permissionText}>Foreground location is requested only after tapping below. Postcode mode uses outward-code matching and does not claim precise mileage.</Text><Pressable onPress={()=>void device()} disabled={locating} style={styles.locate}><Ionicons name="locate" size={17} color={FateDropColors.text}/><Text style={styles.locateText}>{locating?'Locating events…':'Use my location'}</Text></Pressable><View style={styles.manual}><TextInput value={postcode} onChangeText={setPostcode} autoCapitalize="characters" placeholder="UK postcode" placeholderTextColor={FateDropColors.muted} style={styles.input}/><Pressable onPress={()=>void manual()} style={styles.go}><Text style={styles.locateText}>Set</Text></Pressable></View>{error?<Text style={styles.error}>{error}</Text>:null}{area?<StatusBadge label={area.source==='DEVICE'?'Device distance enabled':`Postcode area ${outward(area.postcode)}`} color={FateDropColors.mint}/>:null}</View><Text style={styles.heading}>Date range</Text><View style={styles.filters}>{(['all','30','90'] as DateWindow[]).map(value=><FilterChip key={value} label={value==='all'?'All dates':`Next ${value} days`} active={dateWindow===value} onPress={()=>setDateWindow(value)}/>)}</View>{area?.source==='DEVICE'?<><Text style={styles.heading}>Radius</Text><View style={styles.filters}>{[10,25,50,100].map(value=><FilterChip key={value} label={`${value} miles`} active={radius===value} onPress={()=>setRadius(value)}/>)}</View></>:null}<Text style={styles.heading}>Event type</Text><FlatList horizontal data={types} keyExtractor={item=>item} renderItem={({item})=><FilterChip label={item} active={eventType===item} onPress={()=>setEventType(item)}/>} contentContainerStyle={styles.horizontal} showsHorizontalScrollIndicator={false}/><Text style={styles.heading}>Organiser</Text><FlatList horizontal data={organisers} keyExtractor={item=>item} renderItem={({item})=><FilterChip label={item} active={organiser===item} onPress={()=>setOrganiser(item)}/>} contentContainerStyle={styles.horizontal} showsHorizontalScrollIndicator={false}/><View style={styles.listHeading}><Text style={styles.heading}>Upcoming activity</Text><StatusBadge label={`${filtered.length} results`} color={FateDropColors.cyan}/></View></>;
  return <SafeAreaView style={styles.safe}><FateDropBackground/><FlatList data={filtered} keyExtractor={item=>item.id} contentContainerStyle={styles.content} ListHeaderComponent={header} ListEmptyComponent={<Text style={styles.empty}>No shops or events match this location and filter combination.</Text>} renderItem={({item})=><Pressable onPress={()=>item.kind==='SHOP'&&item.retailerId?router.push({pathname:'/retailers/[id]',params:{id:item.retailerId}}):router.push({pathname:'/encounters/detail',params:{id:item.id}})} style={styles.card}><View style={styles.eventIcon}><Ionicons name={item.kind==='SHOP'?'storefront':'calendar'} size={20} color={FateDropColors.violetLight}/></View><View style={{flex:1}}><Text style={styles.eventName}>{item.name}</Text><Text style={styles.eventMeta}>{item.kind==='SHOP'?'Physical card shop · nearby stock entry':`${item.startDateTime?new Date(item.startDateTime).toLocaleDateString('en-GB'):'Date TBC'} · ${item.venueName||item.townCity||'Venue TBC'}`}</Text><Text style={styles.eventMeta}>{item.distanceMiles!==undefined?`${item.distanceMiles.toFixed(1)} miles · `:''}{item.postcode||'Location pending'}</Text></View><Ionicons name="chevron-forward" size={17} color={FateDropColors.muted}/></Pressable>}/></SafeAreaView>;
}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:FateDropColors.background},content:{paddingHorizontal:20,paddingBottom:80},back:{flexDirection:'row',gap:8,alignItems:'center',paddingVertical:12},backText:{color:FateDropColors.text,fontWeight:'800'},permission:{padding:15,borderRadius:19,backgroundColor:FateDropColors.glass,borderWidth:1,borderColor:FateDropColors.border},permissionTitle:{color:FateDropColors.text,fontWeight:'900'},permissionText:{color:FateDropColors.secondary,fontSize:11,lineHeight:17,marginVertical:7},locate:{flexDirection:'row',justifyContent:'center',gap:7,padding:12,borderRadius:13,backgroundColor:FateDropColors.violet},locateText:{color:FateDropColors.text,fontWeight:'900'},manual:{flexDirection:'row',gap:8,marginTop:9},input:{flex:1,color:FateDropColors.text,padding:11,borderRadius:12,backgroundColor:FateDropColors.cardElevated},go:{justifyContent:'center',paddingHorizontal:18,borderRadius:12,backgroundColor:FateDropColors.cardElevated},error:{color:FateDropColors.coral,fontSize:10,marginTop:8},heading:{color:FateDropColors.text,fontSize:18,fontWeight:'900',marginVertical:15},filters:{flexDirection:'row',flexWrap:'wrap',gap:8},horizontal:{gap:8,paddingBottom:4},listHeading:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},card:{flexDirection:'row',alignItems:'center',gap:11,padding:14,borderRadius:17,backgroundColor:FateDropColors.glass,borderWidth:1,borderColor:FateDropColors.border,marginBottom:9},eventIcon:{width:42,height:42,borderRadius:13,alignItems:'center',justifyContent:'center',backgroundColor:`${FateDropColors.violetLight}12`},eventName:{color:FateDropColors.text,fontWeight:'900'},eventMeta:{color:FateDropColors.muted,fontSize:10,marginTop:4},empty:{color:FateDropColors.muted,textAlign:'center',margin:35}});
