import { Ionicons } from '@expo/vector-icons';
import { ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { AbstractHero, FateDropBackground, PageNavigation, StatusBadge } from '@/components/fatedrop-ui';
import { FateDropColors } from '@/constants/theme';

const benefits=[
  {icon:'globe-outline',title:'Worldwide discovery',copy:'Place your available Pokémon catalogue in front of collectors beyond your existing audience.',color:FateDropColors.violetLight},
  {icon:'sync-outline',title:'Live catalogue connection',copy:'Keep pricing, availability and direct product links current through a verified store feed.',color:FateDropColors.cyan},
  {icon:'navigate-outline',title:'Traffic goes to your shop',copy:'Every available listing links collectors directly to the retailer checkout experience.',color:FateDropColors.mint},
] as const;
export default function RetailerPartners(){return <SafeAreaView style={styles.safe}><FateDropBackground/><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><PageNavigation/><AbstractHero eyebrow="Retailer partners" title="Small shops. Worldwide reach." subtitle="Join FateDrop's live Pokémon catalogue and help collectors discover what your store has available now." icon="storefront"/><View style={styles.status}><StatusBadge label="Partner programme" color={FateDropColors.violetLight}/><Text style={styles.statusText}>Applications opening soon</Text></View><Text style={styles.heading}>Built for independent retailers</Text><Text style={styles.intro}>FateDrop is building one searchable view of live Pokémon stock across trusted retailers. Partner stores pay a listing fee for verified catalogue distribution and direct customer discovery.</Text><View style={styles.list}>{benefits.map(item=><View key={item.title} style={styles.card}><View style={[styles.icon,{backgroundColor:`${item.color}16`,borderColor:`${item.color}44`}]}><Ionicons name={item.icon} size={20} color={item.color}/></View><View style={styles.copy}><Text style={styles.title}>{item.title}</Text><Text style={styles.body}>{item.copy}</Text></View></View>)}</View><View style={styles.requirements}><Text style={styles.requirementsEyebrow}>PARTNER STANDARD</Text><Text style={styles.requirementsTitle}>Accurate stock earns collector trust.</Text><Text style={styles.requirementsCopy}>Stores will need an active online catalogue, direct product URLs, reliable availability data and UK or international fulfilment details.</Text></View></ScrollView></SafeAreaView>}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:FateDropColors.background},content:{paddingHorizontal:20,paddingBottom:70},status:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginBottom:20},statusText:{color:FateDropColors.amber,fontSize:10,fontWeight:'800',textTransform:'uppercase',letterSpacing:.8},heading:{color:FateDropColors.text,fontSize:24,fontWeight:'900',letterSpacing:-.6},intro:{color:FateDropColors.secondary,fontSize:14,lineHeight:22,marginTop:9,marginBottom:18},list:{gap:10},card:{flexDirection:'row',gap:13,backgroundColor:FateDropColors.glass,borderWidth:1,borderColor:FateDropColors.border,borderRadius:20,padding:15},icon:{width:43,height:43,borderRadius:14,alignItems:'center',justifyContent:'center',borderWidth:1},copy:{flex:1},title:{color:FateDropColors.text,fontSize:15,fontWeight:'800'},body:{color:FateDropColors.muted,fontSize:12,lineHeight:18,marginTop:4},requirements:{marginTop:20,padding:20,borderRadius:22,backgroundColor:'rgba(30,21,47,.92)',borderWidth:1,borderColor:`${FateDropColors.violetLight}44`},requirementsEyebrow:{color:FateDropColors.cyan,fontSize:9,fontWeight:'900',letterSpacing:1.5},requirementsTitle:{color:FateDropColors.text,fontSize:19,fontWeight:'900',marginTop:8},requirementsCopy:{color:FateDropColors.secondary,fontSize:12,lineHeight:19,marginTop:7}});
