import { Ionicons } from '@expo/vector-icons';
import { useFocusEffect } from 'expo-router';
import { useCallback, useMemo, useState } from 'react';
import { ActivityIndicator, FlatList, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { AbstractHero, FateDropBackground, FateDropHeader, FilterChip, ProductCard, StatusBadge } from '@/components/fatedrop-ui';
import { RetailerCard } from '@/components/retailer-card';
import { retailers } from '@/constants/retailers';
import { FateDropColors } from '@/constants/theme';
import { useCatalogue } from '@/hooks/use-catalogue';
import { loadWatchlist, toggleWatchlist } from '@/lib/watchlist';
import { openTrackedRetailerLink } from '@/services/outbound-links';
import type { ProductCategory } from '@/types/domain';

const categories: {label:string;value?:ProductCategory}[]=[{label:'All'},{label:'Sealed',value:'SEALED'},{label:'Singles',value:'SINGLE'},{label:'Graded',value:'GRADED'},{label:'Accessories',value:'ACCESSORY'},{label:'Preorders',value:'PREORDER'}];
type DirectoryFilter='all'|'online'|'physical'|'verified'|'collection';

export default function IndiesScreen(){
  const [mode,setMode]=useState<'directory'|'catalogue'>('directory');
  const [directoryQuery,setDirectoryQuery]=useState('');
  const [directoryFilter,setDirectoryFilter]=useState<DirectoryFilter>('all');
  const [query,setQuery]=useState('');
  const [category,setCategory]=useState<ProductCategory>();
  const [condition,setCondition]=useState<string>();
  const [setName,setSetName]=useState('');
  const [minimumPrice,setMinimumPrice]=useState('');
  const [maximumPrice,setMaximumPrice]=useState('');
  const [sort,setSort]=useState<'title'|'price'|'newest'|'popularity'|'distance'>('title');
  const [retailerId,setRetailerId]=useState<string>();
  const [watched,setWatched]=useState<string[]>([]);
  useFocusEffect(useCallback(()=>{void loadWatchlist().then(setWatched)},[]));
  const networkRetailers=useMemo(()=>retailers.filter(item=>item.id!=='pokemon-center-uk'),[]);
  const directoryRetailers=useMemo(()=>networkRetailers.filter(item=>{
    const term=directoryQuery.trim().toLowerCase();
    const location=item.locations.map(value=>`${value.townCity||''} ${value.postcode||''}`).join(' ').toLowerCase();
    if(term&&!item.name.toLowerCase().includes(term)&&!location.includes(term))return false;
    if(directoryFilter==='online')return item.onlineOnly;
    if(directoryFilter==='physical')return !item.onlineOnly;
    if(directoryFilter==='verified')return item.verification.status==='VERIFIED';
    if(directoryFilter==='collection')return item.locations.some(value=>value.collectionAvailable);
    return true;
  }),[directoryFilter,directoryQuery,networkRetailers]);
  const catalogue=useCatalogue({query,category,condition,setName,minimumPriceGbp:minimumPrice?Number(minimumPrice):undefined,maximumPriceGbp:maximumPrice?Number(maximumPrice):undefined,sort:sort==='popularity'||sort==='distance'?'title':sort,retailerId,inStockOnly:true,limit:50});
  const commonHeader=<><FateDropHeader title="Indies" rightAction={<StatusBadge label={`${networkRetailers.length} stores`} color={FateDropColors.cyan}/>}/><AbstractHero eyebrow="Independent network" title="Find it local. Support small." subtitle="Search connected stock, discover trusted retailers and buy directly from their websites." icon="storefront"/><View style={styles.mode}><FilterChip label="Retailers" active={mode==='directory'} onPress={()=>setMode('directory')}/><FilterChip label="Live catalogue" active={mode==='catalogue'} onPress={()=>setMode('catalogue')}/></View></>;
  if(mode==='directory')return <SafeAreaView style={styles.safe}><FateDropBackground/><FlatList data={directoryRetailers} keyExtractor={item=>item.id} contentContainerStyle={styles.content} ItemSeparatorComponent={()=> <View style={{height:10}}/>} ListHeaderComponent={<>{commonHeader}<View style={styles.search}><Ionicons name="search" size={18} color={FateDropColors.muted}/><TextInput value={directoryQuery} onChangeText={setDirectoryQuery} placeholder="Search name, town or postcode" placeholderTextColor={FateDropColors.muted} style={styles.input}/></View><FlatList horizontal data={['all','online','physical','verified','collection'] as DirectoryFilter[]} keyExtractor={item=>item} renderItem={({item})=><FilterChip label={item==='all'?'All':item==='online'?'Online only':item==='physical'?'Physical shops':item==='verified'?'Verified':'Collection'} active={directoryFilter===item} onPress={()=>setDirectoryFilter(item)}/>} contentContainerStyle={styles.filters} showsHorizontalScrollIndicator={false}/><Text style={styles.resultCount}>{directoryRetailers.length} matching retailers</Text></>} ListEmptyComponent={<Text style={styles.state}>No retailers match these filters.</Text>} renderItem={({item})=><RetailerCard retailer={item}/>}/></SafeAreaView>;
  const catalogueHeader=<>{commonHeader}<View style={styles.search}><Ionicons name="search" size={18} color={FateDropColors.muted}/><TextInput value={query} onChangeText={setQuery} placeholder="Search network stock" placeholderTextColor={FateDropColors.muted} style={styles.input}/></View><FlatList horizontal data={categories} keyExtractor={item=>item.label} renderItem={({item})=><FilterChip label={item.label} active={category===item.value} onPress={()=>setCategory(item.value)}/>} contentContainerStyle={styles.filters} showsHorizontalScrollIndicator={false}/><FlatList horizontal data={[{id:undefined,name:'All retailers'},...networkRetailers]} keyExtractor={item=>item.id||'all'} renderItem={({item})=><FilterChip label={item.name} active={retailerId===item.id} onPress={()=>setRetailerId(item.id)}/>} contentContainerStyle={styles.filters} showsHorizontalScrollIndicator={false}/><Text style={styles.filterLabel}>Condition</Text><View style={styles.chips}>{['NEAR_MINT','LIGHTLY_PLAYED','GRADED','NEW'].map(value=><FilterChip key={value} label={value.replaceAll('_',' ')} active={condition===value} onPress={()=>setCondition(condition===value?undefined:value)}/>)}</View><Text style={styles.filterLabel}>Set and price</Text><View style={styles.range}><TextInput value={setName} onChangeText={setSetName} placeholder="Set name" placeholderTextColor={FateDropColors.muted} style={styles.rangeInput}/><TextInput value={minimumPrice} onChangeText={setMinimumPrice} keyboardType="decimal-pad" placeholder="Min £" placeholderTextColor={FateDropColors.muted} style={styles.rangeInput}/><TextInput value={maximumPrice} onChangeText={setMaximumPrice} keyboardType="decimal-pad" placeholder="Max £" placeholderTextColor={FateDropColors.muted} style={styles.rangeInput}/></View><Text style={styles.filterLabel}>Sort</Text><View style={styles.chips}>{(['title','price','newest','popularity','distance'] as const).map(value=><FilterChip key={value} label={value} active={sort===value} onPress={()=>setSort(value)}/>)}</View>{sort==='popularity'||sort==='distance'?<Text style={styles.unavailable}>{sort} data is not available for these offers; title order is retained.</Text>:null}<View style={styles.summary}><Text style={styles.resultCount}>{catalogue.total.toLocaleString()} matching products</Text><Text style={styles.note}>Sold out hidden</Text></View></>;
  return <SafeAreaView style={styles.safe}><FateDropBackground/><FlatList data={catalogue.offers} keyExtractor={item=>item.id} ListHeaderComponent={catalogueHeader} contentContainerStyle={styles.content} ItemSeparatorComponent={()=> <View style={{height:10}}/>} onEndReached={()=>void catalogue.loadMore()} onEndReachedThreshold={.5} ListFooterComponent={catalogue.loadingMore?<ActivityIndicator color={FateDropColors.violetLight} style={styles.state}/>:null} ListEmptyComponent={catalogue.loading?<ActivityIndicator color={FateDropColors.violetLight} style={styles.state}/>:<Text style={styles.state}>{catalogue.error||'No matching live products.'}</Text>} renderItem={({item})=>{const store=retailers.find(value=>value.id===item.retailerId),shipping=item.shippingOptions.find(option=>!option.collection)?.priceGbp,details=[item.setName,item.cardNumber,item.condition.replaceAll('_',' '),shipping===undefined?'Delivery unknown':`Delivery £${shipping.toFixed(2)}`].filter(Boolean).join(' · ');return <ProductCard title={item.title} retailer={store?.name||item.retailerId} details={details} price={item.priceGbp===undefined?'Price unavailable':`£${item.priceGbp.toFixed(2)}`} stockLabel={item.preorder?'Preorder':'In stock'} stockTone="mint" fateLabel={item.pulseLabels?.[0]?.replaceAll('_',' ')} fateTone={item.pulseLabels?.includes('PRICE_DROPPED')?'mint':'violet'} imageSource={item.imageUrl?{uri:item.imageUrl}:undefined} productUrl={item.productUrl} onOpenProduct={item.productUrl?()=>void openTrackedRetailerLink({destinationUrl:item.productUrl!,retailerId:item.retailerId,offerId:item.id,placement:'indies-catalogue'}):undefined} inWatchlist={watched.includes(item.id)} onToggleWatchlist={()=>void toggleWatchlist(item.id,watched).then(setWatched)}/>}}/></SafeAreaView>;
}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:FateDropColors.background},content:{paddingHorizontal:20,paddingBottom:120},mode:{flexDirection:'row',gap:8,marginBottom:15},search:{flexDirection:'row',alignItems:'center',gap:10,padding:12,borderRadius:18,backgroundColor:FateDropColors.glass,borderWidth:1,borderColor:FateDropColors.border,marginBottom:12},input:{flex:1,color:FateDropColors.text},filters:{gap:8,paddingBottom:12},filterLabel:{color:FateDropColors.cyan,fontSize:9,fontWeight:'900',textTransform:'uppercase',marginBottom:7},chips:{flexDirection:'row',flexWrap:'wrap',gap:7,marginBottom:12},range:{flexDirection:'row',gap:7,marginBottom:12},rangeInput:{flex:1,color:FateDropColors.text,padding:10,borderRadius:12,backgroundColor:FateDropColors.cardElevated},unavailable:{color:FateDropColors.amber,fontSize:9,lineHeight:14,marginBottom:10},resultCount:{color:FateDropColors.text,fontWeight:'800',marginBottom:13},summary:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},note:{color:FateDropColors.muted,fontSize:10,marginBottom:13},state:{color:FateDropColors.muted,textAlign:'center',margin:35}});
