import AsyncStorage from '@react-native-async-storage/async-storage';
import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { useCallback,useEffect,useMemo,useState } from 'react';
import { ActivityIndicator,Pressable,RefreshControl,ScrollView,StyleSheet,Text,View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { FateDropBackground,FateDropHeader,FilterChip,PageNavigation,StatusBadge } from '@/components/fatedrop-ui';
import { API_BASE_URL } from '@/constants/api';import { FateDropColors } from '@/constants/theme';
import { formatEventDate,loadSavedEventIds,saveEventIds } from '@/lib/encounters';import type { CalendarEvent } from '@/types/encounter';
const filters=['All','Region','This Month','Pokémon','All TCG','Free Entry','Vendor Spaces','Saved'] as const;
export default function EncountersScreen(){const[events,setEvents]=useState<CalendarEvent[]>([]),[saved,setSaved]=useState<string[]>([]),[active,setActive]=useState<(typeof filters)[number]>('All'),[region,setRegion]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState(''),[refreshing,setRefreshing]=useState(false);
 const load=useCallback(async()=>{try{setError('');const response=await fetch(`${API_BASE_URL}/api/calendar-events`);if(!response.ok)throw new Error('Request failed');const data=await response.json();setEvents(Array.isArray(data.events)?data.events:[])}catch{setError('Fate Encounters could not be loaded.')}finally{setLoading(false);setRefreshing(false)}},[]);
 useEffect(()=>{load();loadSavedEventIds(AsyncStorage).then(setSaved)},[load]);
 const toggle=async(id:string)=>{const next=saved.includes(id)?saved.filter(x=>x!==id):[...saved,id];setSaved(next);await saveEventIds(AsyncStorage,next)};
 const regions=useMemo(()=>[...new Set(events.map(e=>e.region).filter((value):value is string=>Boolean(value)))].sort(),[events]);
 const shown=useMemo(()=>events.filter(e=>{if(active==='Saved')return saved.includes(e.id);if(active==='Region')return !region||e.region===region;if(active==='This Month'){const n=new Date();return e.startDateTime.slice(0,7)===`${n.getFullYear()}-${String(n.getMonth()+1).padStart(2,'0')}`}if(active==='Pokémon')return e.supportedTcgs?.includes('Pokémon');if(active==='All TCG')return e.supportedTcgs?.includes('All TCG');if(active==='Free Entry')return /free/i.test(e.ticketPriceText||'');if(active==='Vendor Spaces')return e.vendorApplicationsStatus==='open';return true}),[active,events,region,saved]);const featured=shown.find(e=>e.featured);
 const card=(e:CalendarEvent,hero=false)=><Pressable key={e.id} accessibilityRole="button" accessibilityLabel={`Open ${e.name}`} onPress={()=>router.push({pathname:'/encounters/detail',params:{id:e.id,eventData:JSON.stringify(e)}})} style={({pressed})=>[styles.card,hero&&styles.featured,pressed&&styles.pressed]}><View style={styles.cardTop}><Text style={styles.cardTitle}>{e.name}</Text><Pressable accessibilityLabel={saved.includes(e.id)?'Unsave event':'Save event'} hitSlop={10} onPress={event=>{event.stopPropagation();toggle(e.id)}}><Ionicons name={saved.includes(e.id)?'bookmark':'bookmark-outline'} size={21} color={FateDropColors.violetLight}/></Pressable></View><Text style={styles.date}>{formatEventDate(e.startDateTime,e.endDateTime)}</Text><Text style={styles.place}>{e.venueName||e.townCity||'Venue to be confirmed'}</Text><Text style={styles.price}>{e.ticketPriceText||'Price to be confirmed'}</Text><View style={styles.tags}>{e.featured?<StatusBadge label="Featured" color={FateDropColors.amber}/>:null}{e.verificationStatus==='verified'?<StatusBadge label="Verified" color={FateDropColors.mint}/>:null}{e.vendorApplicationsStatus==='open'?<StatusBadge label="Vendor spaces" color={FateDropColors.blue}/>:null}</View></Pressable>;
 return <SafeAreaView style={styles.safe}><FateDropBackground/><ScrollView contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>{setRefreshing(true);load()}} tintColor={FateDropColors.violetLight}/>}><PageNavigation/><FateDropHeader title="Fate Encounters"/><Text style={styles.intro}>Discover card shows, vendors and collector events across the UK.</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.filters}>{filters.map(f=><FilterChip key={f} label={f} active={active===f} onPress={()=>setActive(f)}/>)}</ScrollView>{active==='Region'?<ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.regionFilters}>{regions.map(value=><FilterChip key={value} label={value} active={region===value} onPress={()=>setRegion(value)}/>)}</ScrollView>:null}{loading?<ActivityIndicator color={FateDropColors.violetLight} style={styles.state}/>:error?<View style={styles.state}><Text style={styles.error}>{error}</Text><Pressable onPress={()=>{setLoading(true);load()}}><Text style={styles.retry}>Retry</Text></Pressable></View>:shown.length===0?<Text style={styles.stateText}>No upcoming encounters match this filter.</Text>:<>{featured?<><Text style={styles.heading}>Featured encounter</Text>{card(featured,true)}</>:null}<Text style={styles.heading}>Upcoming</Text>{shown.filter(e=>e.id!==featured?.id).map(e=>card(e))}</>}</ScrollView></SafeAreaView>}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:FateDropColors.background},content:{paddingHorizontal:20,paddingBottom:80},intro:{color:FateDropColors.secondary,fontSize:14,lineHeight:21,marginBottom:16,padding:16,borderRadius:18,backgroundColor:'rgba(19,17,31,.82)',borderWidth:1,borderColor:`${FateDropColors.violetLight}33`},filters:{gap:8,paddingBottom:18},regionFilters:{gap:8,paddingBottom:12},heading:{color:FateDropColors.text,fontSize:21,fontWeight:'900',letterSpacing:-.4,marginVertical:14},card:{backgroundColor:FateDropColors.glass,borderWidth:1,borderColor:FateDropColors.border,borderRadius:22,padding:17,marginBottom:12,shadowColor:'#000',shadowOpacity:.24,shadowRadius:12,shadowOffset:{width:0,height:7},elevation:3},featured:{borderColor:`${FateDropColors.violetLight}88`,backgroundColor:'rgba(38,24,57,0.94)',shadowColor:FateDropColors.violet,shadowOpacity:.3},cardTop:{flexDirection:'row',gap:12,alignItems:'flex-start'},cardTitle:{flex:1,color:FateDropColors.text,fontSize:18,fontWeight:'900',lineHeight:23},date:{color:FateDropColors.cyan,fontWeight:'800',marginTop:9},place:{color:FateDropColors.secondary,marginTop:6,lineHeight:18},price:{color:FateDropColors.text,fontWeight:'800',marginTop:8},tags:{flexDirection:'row',flexWrap:'wrap',gap:6,marginTop:12},state:{marginTop:60,alignItems:'center'},stateText:{color:FateDropColors.muted,textAlign:'center',marginTop:60},error:{color:FateDropColors.coral,textAlign:'center'},retry:{color:FateDropColors.violetLight,fontWeight:'800',marginTop:14},pressed:{opacity:.8,transform:[{scale:.99}]}});

