const STAGES={WHISPER:"WHISPER",MANIFESTED:"MANIFESTED",VANISHED:"VANISHED",ECHO:"ECHO",UNKNOWN:"UNKNOWN"};
const stock=p=>p?.availability==="IN_STOCK";
function migrateProduct(p,n=new Date().toISOString()){const f=p.firstSeen||p.lastSeen||n,l=p.lastSeen||f;return{...p,firstSeen:f,lastSeen:l,firstInStockAt:p.firstInStockAt||(stock(p)?f:null),lastInStockAt:p.lastInStockAt||(stock(p)?l:null),vanishedAt:p.vanishedAt||null,returnedAt:p.returnedAt||null,fateStage:p.fateStage||(stock(p)?STAGES.MANIFESTED:STAGES.UNKNOWN),previousFateStage:p.previousFateStage||null,timesRestocked:Number.isInteger(p.timesRestocked)?p.timesRestocked:0,isCurrentlyListed:p.isCurrentlyListed!==false}}
function normaliseProduct(r,o=null,n=new Date().toISOString()){let a=r.availability_status??r.availability??"UNKNOWN";if(Array.isArray(a))a=a[0];const validUrl=typeof r.url==="string"&&/^https?:\/\//i.test(r.url)?r.url:null;return{...(o||{}),sku:r.pid||r.sku,title:r.title||r.reporting_product_name||o?.title||"Unknown product",retailer:r.retailer||o?.retailer||"Pokémon Center UK",retailerKey:r.retailerKey||o?.retailerKey||"pokemon-center-uk",availability:a||"UNKNOWN",price:r.sale_price??r.price??o?.price??null,launchDate:r.launch_date??r.launchDate??o?.launchDate??null,url:validUrl??o?.url??null,image:r.primary_image_full_size||r.primary_image||r.thumb_image||r.image||o?.image||null,firstSeen:o?.firstSeen||n,lastSeen:n,isCurrentlyListed:true}}
function makeEvent(type,stage,old,p,previousValues,n){const priority=["RESTOCK","NEW_PRODUCT_LIVE"].includes(type)?"CRITICAL":type==="NEW_PRODUCT"?"EARLY":type==="SOLD_OUT"?"INFO":"LOW";const names={NEW_PRODUCT:"A whisper in the catalogue",NEW_PRODUCT_LIVE:"A new fate has manifested",RESTOCK:"Fate Echo",SOLD_OUT:"A fate has vanished",LISTING_REMOVED:"Listing no longer present",PRICE_CHANGE:"Price changed",RELEASE_DATE_CHANGE:"Release date changed"};const fingerprint=[p.retailerKey,p.sku,type,stage,JSON.stringify(previousValues),p.availability,p.price,p.launchDate].join("|");return{id:[fingerprint,n].join("|"),fingerprint,sku:p.sku,type,fateStage:stage,previousFateStage:old||null,priority,detectedAt:n,retailer:p.retailer||"Pokémon Center UK",product:{...p},title:names[type],message:`${names[type]}: ${p.title}`,previousValues}}
function transitionProduct(previous,current,n=new Date().toISOString()){const o=previous?migrateProduct(previous,n):null,p=normaliseProduct(current,o,n),events=[];let stage=o?.fateStage||STAGES.UNKNOWN,type=null;if(!o){stage=stock(p)?STAGES.MANIFESTED:STAGES.WHISPER;type=stock(p)?"NEW_PRODUCT_LIVE":"NEW_PRODUCT"}else if(!stock(o)&&stock(p)){stage=o.vanishedAt||o.firstInStockAt?STAGES.ECHO:STAGES.MANIFESTED;type=stage===STAGES.ECHO?"RESTOCK":"NEW_PRODUCT_LIVE"}else if(stock(o)&&!stock(p)){stage=STAGES.VANISHED;type="SOLD_OUT"}Object.assign(p,{previousFateStage:o?.fateStage||null,fateStage:stage,firstInStockAt:o?.firstInStockAt||(stock(p)?n:null),lastInStockAt:stock(p)?n:o?.lastInStockAt||null,vanishedAt:type==="SOLD_OUT"?n:o?.vanishedAt||null,returnedAt:stage===STAGES.ECHO?n:o?.returnedAt||null,timesRestocked:(o?.timesRestocked||0)+(stage===STAGES.ECHO?1:0)});if(type)events.push(makeEvent(type,stage,o?.fateStage,p,o?{availability:o.availability}:{},n));if(o?.price!=null&&p.price!=null&&Number(o.price)!==Number(p.price))events.push(makeEvent("PRICE_CHANGE",stage,o.fateStage,p,{price:o.price},n));if(o?.launchDate&&p.launchDate&&o.launchDate!==p.launchDate)events.push(makeEvent("RELEASE_DATE_CHANGE",stage,o.fateStage,p,{launchDate:o.launchDate},n));return{product:p,events}}
function compareProducts(previous={},scanned={},options={}){const n=options.now||new Date().toISOString();if(options.scanVerified!==true)return{committed:false,products:previous,events:[]};const products={},events=[],scope=options.retailerKey||null;for(const[sku,p]of Object.entries(previous))products[sku]=migrateProduct(p,n);for(const[sku,p]of Object.entries(scanned)){const r=transitionProduct(products[sku],p,n);products[sku]=r.product;events.push(...r.events)}for(const[sku,p]of Object.entries(products)){if(Object.prototype.hasOwnProperty.call(scanned,sku))continue;if(scope&&(p.retailerKey||"pokemon-center-uk")!==scope)continue;const listed=p.isCurrentlyListed!==false,stage=stock(p)?STAGES.VANISHED:p.fateStage;products[sku]={...p,isCurrentlyListed:false,fateStage:stage,previousFateStage:p.fateStage,vanishedAt:stock(p)?n:p.vanishedAt};if(listed)events.push(makeEvent("LISTING_REMOVED",stage,p.fateStage,products[sku],{isCurrentlyListed:true},n))}return{committed:true,products,events}}
function mergeEventHistory(existing,incoming,limit=500){const history=Array.isArray(existing)?existing.filter(e=>e&&e.id):[],seen=new Set(history.map(e=>e.fingerprint||e.id));return[...incoming.filter(e=>!seen.has(e.fingerprint||e.id)),...history].slice(0,limit)}
module.exports={FATE_STAGES:STAGES,isInStock:stock,migrateProduct,normaliseProduct,transitionProduct,compareProducts,mergeEventHistory};
