import { Ionicons } from '@expo/vector-icons';
import { router, useLocalSearchParams } from 'expo-router';
import { FlatList, Linking, Pressable, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { AbstractHero, FateDropBackground, ProductCard, StatusBadge } from '@/components/fatedrop-ui';
import { retailers } from '@/constants/retailers';
import { FateDropColors } from '@/constants/theme';
import { useCatalogue } from '@/hooks/use-catalogue';
import { openTrackedRetailerLink } from '@/services/outbound-links';

export default function RetailerStorefront(){
  const {id}=useLocalSearchParams<{id:string}>();
  const retailer=retailers.find(item=>item.id===id);
  const catalogue=useCatalogue({retailerId:id,inStockOnly:true,limit:50});
  if(!retailer)return <SafeAreaView style={styles.safe}><Text style={styles.missing}>Retailer could not be found.</Text></SafeAreaView>;
  const location=retailer.locations[0];
  const postcode=location?.postcode;
  const address=location?[location.addressLine1,location.townCity,location.postcode].filter(Boolean).join(', '):'';
  const header=<><Pressable onPress={()=>router.back()} style={styles.back}><Ionicons name="arrow-back" size={20} color={FateDropColors.text}/><Text style={styles.backText}>Indies</Text></Pressable><AbstractHero eyebrow={retailer.isDemo?'Demo retailer':retailer.verification.status==='VERIFIED'?'Verified store':'Retailer profile'} title={retailer.name} subtitle={retailer.description||'Connected UK Pokémon retailer.'} icon="storefront"/>{retailer.isDemo?<View style={styles.demo}><StatusBadge label="Fictional demo business" color={FateDropColors.amber}/></View>:null}<View style={styles.actions}><Pressable onPress={()=>void Linking.openURL(retailer.websiteUrl)} style={styles.primary}><Text style={styles.primaryText}>Visit retailer</Text><Ionicons name="open-outline" size={15} color={FateDropColors.text}/></Pressable>{postcode?<Pressable onPress={()=>void Linking.openURL(`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(postcode)}`)} style={styles.secondary}><Text style={styles.secondaryText}>Map</Text></Pressable>:null}</View><View style={styles.badges}><StatusBadge label={retailer.onlineOnly?'Online retailer':'Physical store'} color={FateDropColors.cyan}/><StatusBadge label={retailer.verification.status==='VERIFIED'?'Verified business':'Verification not established'} color={retailer.verification.status==='VERIFIED'?FateDropColors.mint:FateDropColors.muted}/>{location?.collectionAvailable?<StatusBadge label="Collection available" color={FateDropColors.mint}/>:null}</View><View style={styles.information}><Info label="Address" value={address||'No physical-shop address supplied'}/><Info label="Opening hours" value={location?.openingHours?Object.entries(location.openingHours).map(([day,hours])=>`${day}: ${hours}`).join(' · '):'Not supplied by retailer'}/><Info label="Delivery" value={retailer.deliveryInformation||'Delivery information not supplied'}/><Info label="Verification" value={retailer.verification.status==='VERIFIED'?`Business verified${retailer.verification.lastReviewedAt?` · reviewed ${new Date(retailer.verification.lastReviewedAt).toLocaleDateString('en-GB')}`:''}`:'Verification has not been established'}/><Pressable onPress={()=>router.push('/fatescore')}><Text style={styles.scoreLink}>How FateScore works</Text></Pressable></View><View style={styles.eventPanel}><Text style={styles.sectionTitle}>Upcoming retailer events</Text><Text style={styles.emptyCopy}>No retailer-hosted events are currently connected to this profile.</Text></View><Text style={styles.sectionTitle}>Available now · {catalogue.total.toLocaleString()}</Text></>;
  return <SafeAreaView style={styles.safe}><FateDropBackground/><FlatList data={catalogue.offers} keyExtractor={item=>item.id} onEndReached={()=>void catalogue.loadMore()} contentContainerStyle={styles.content} ItemSeparatorComponent={()=> <View style={{height:10}}/>} ListHeaderComponent={header} renderItem={({item})=><ProductCard title={item.title} retailer={retailer.name} price={item.priceGbp===undefined?'Price unavailable':`£${item.priceGbp.toFixed(2)}`} stockLabel={item.preorder?'Preorder':'In stock'} stockTone="mint" fateLabel={item.pulseLabels?.[0]?.replaceAll('_',' ')} imageSource={item.imageUrl?{uri:item.imageUrl}:undefined} productUrl={item.productUrl} onOpenProduct={item.productUrl?()=>void openTrackedRetailerLink({destinationUrl:item.productUrl!,retailerId:retailer.id,offerId:item.id,placement:'retailer-storefront'}):undefined}/>} ListEmptyComponent={<Text style={styles.emptyCopy}>{catalogue.loading?'Loading catalogue…':catalogue.error||'No available products.'}</Text>}/></SafeAreaView>;
}
function Info({label,value}:{label:string;value:string}){return <View style={styles.infoRow}><Text style={styles.infoLabel}>{label}</Text><Text style={styles.infoValue}>{value}</Text></View>}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:FateDropColors.background},content:{paddingHorizontal:20,paddingBottom:100},back:{flexDirection:'row',alignItems:'center',gap:8,paddingVertical:12},backText:{color:FateDropColors.text,fontWeight:'800'},demo:{marginBottom:12},actions:{flexDirection:'row',gap:9,marginBottom:13},primary:{flex:1,flexDirection:'row',justifyContent:'center',alignItems:'center',gap:7,padding:13,borderRadius:15,backgroundColor:FateDropColors.violet},primaryText:{color:FateDropColors.text,fontWeight:'900'},secondary:{padding:13,borderRadius:15,borderWidth:1,borderColor:FateDropColors.border},secondaryText:{color:FateDropColors.text,fontWeight:'800'},badges:{flexDirection:'row',flexWrap:'wrap',gap:7},information:{padding:15,borderRadius:18,backgroundColor:FateDropColors.glass,borderWidth:1,borderColor:FateDropColors.border,marginTop:13},infoRow:{marginBottom:11},infoLabel:{color:FateDropColors.cyan,fontSize:9,fontWeight:'900',textTransform:'uppercase'},infoValue:{color:FateDropColors.secondary,fontSize:11,lineHeight:17,marginTop:4},scoreLink:{color:FateDropColors.violetLight,fontWeight:'800',fontSize:11},eventPanel:{padding:15,borderRadius:18,backgroundColor:FateDropColors.glass,borderWidth:1,borderColor:FateDropColors.border,marginTop:13},sectionTitle:{color:FateDropColors.text,fontSize:18,fontWeight:'900',marginVertical:16},emptyCopy:{color:FateDropColors.muted,textAlign:'center',margin:25},missing:{color:FateDropColors.text,padding:30}});
