import { Ionicons } from '@expo/vector-icons';
import { File } from 'expo-file-system';
import { router } from 'expo-router';
import { useMemo, useRef, useState } from 'react';
import { ActivityIndicator, FlatList, Pressable, RefreshControl, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';

import { FateCollectionsArt } from '@/components/fate-collections-art';
import { CollectionsScreen } from '@/components/fate-collections-ui';
import { FateProgressRing, FateSectionHeading } from '@/components/fate-polish-ui';
import { FateDropColors, Fonts } from '@/constants/theme';
import { useCollectionsResource } from '@/hooks/use-collections-resource';
import { isBinderComplete, orderBinders } from '@/lib/fate-collections-view';
import {
  confirmCollectrCsv,
  FateCollectorApiError,
  fetchFateCollectorDashboard,
  previewCollectrCsv,
  setFateCollectorBinderTracked,
  type CollectrPreview,
  type FateCollectorSetBinder,
} from '@/services/fate-collector';
import { fetchFatePriceSets, type FatePriceSet } from '@/services/fate-market';

type BinderFilter = 'all' | 'progress' | 'complete';
type BinderScope = 'mine' | 'all-sets';
type TcgFilter = 'all' | 'pokemon' | 'one-piece';
type BinderListRow = { kind: 'binder'; binder: FateCollectorSetBinder } | { kind: 'set'; set: FatePriceSet };

function pct(value: number | null | undefined) { return value == null || !Number.isFinite(value) ? '—' : `${new Intl.NumberFormat('en-GB', { maximumFractionDigits: 1 }).format(value)}%`; }
function money(value: number | null | undefined, currency: string | null | undefined) { if (value == null || !Number.isFinite(value)) return '—'; try { return new Intl.NumberFormat('en-GB', { style: 'currency', currency: currency || 'GBP', maximumFractionDigits: 2 }).format(value); } catch { return `${value.toFixed(2)} ${currency || 'GBP'}`; } }
function importError(error: unknown) { if (error instanceof FateCollectorApiError && error.status === 404 && error.code === 'NOT_FOUND') return 'Collectr imports are not available right now.'; return error instanceof Error ? error.message : 'Fate Collections could not complete that import.'; }
const readBinders = async () => { const [dashboard, pokemon, onePiece] = await Promise.all([fetchFateCollectorDashboard({ force: true }), fetchFatePriceSets({ tcgCode: 'pokemon', limit: 1000 }).catch(() => ({ sets: [], count: 0 })), fetchFatePriceSets({ tcgCode: 'one-piece', limit: 1000 }).catch(() => ({ sets: [], count: 0 }))]); return { dashboard, sets: [...pokemon.sets, ...onePiece.sets] }; };

export default function FateBindersScreenV2() {
  const { data, loading, error, load } = useCollectionsResource(readBinders);
  const [scope, setScope] = useState<BinderScope>('mine');
  const [filter, setFilter] = useState<BinderFilter>('all');
  const [tcgFilter, setTcgFilter] = useState<TcgFilter>('all');
  const [query, setQuery] = useState('');
  const [sort, setSort] = useState<'progress' | 'name'>('progress');
  const importLock = useRef(false);
  const [preview, setPreview] = useState<CollectrPreview | null>(null);
  const [csvText, setCsvText] = useState('');
  const [importName, setImportName] = useState('');
  const [importWorking, setImportWorking] = useState(false);
  const [importMessage, setImportMessage] = useState('');
  const [trackingSetId, setTrackingSetId] = useState('');

  const allBinders = useMemo(() => orderBinders(data?.dashboard.summary.sets || []), [data?.dashboard.summary.sets]);
  const completed = allBinders.filter(isBinderComplete);
  const inProgress = allBinders.filter((set) => !isBinderComplete(set));
  const visible = orderBinders(filter === 'complete' ? completed : filter === 'progress' ? inProgress : allBinders, query, sort);
  const closest = inProgress.find((set) => set.status === 'available' && Number(set.totalCount) > 0 && Number(set.ownedCount) > 0) || null;
  const currency = closest?.value?.currencyCode || data?.dashboard.summary.currencyCode || 'GBP';
  const topNeeded = closest?.missingCards?.slice(0, 3) || [];
  const binderBySet = useMemo(() => new Map(allBinders.map((binder) => [binder.setId, binder])), [allBinders]);
  const availableSets = useMemo(() => {
    const q = query.trim().toLowerCase();
    const unique = new Map((data?.sets || []).map((set) => [set.id, set]));
    return [...unique.values()].filter((set) => (!q || `${set.name} ${set.seriesName || ''}`.toLowerCase().includes(q)) && (tcgFilter === 'all' || set.tcgCode === tcgFilter)).sort((a, b) => Number(b.releasedAt || 0) - Number(a.releasedAt || 0) || a.name.localeCompare(b.name));
  }, [data?.sets, query, tcgFilter]);
  const listRows: BinderListRow[] = scope === 'mine' ? visible.map((binder) => ({ kind: 'binder', binder })) : availableSets.map((set) => ({ kind: 'set', set }));

  const trackSet = async (set: FatePriceSet) => { if (trackingSetId) return; setTrackingSetId(set.id); try { await setFateCollectorBinderTracked(set.id, true); await load(); router.push({ pathname: '/binder/[setId]', params: { setId: set.id, setName: set.name } }); } catch (caught) { setImportMessage(caught instanceof Error ? caught.message : 'That binder could not be started.'); } finally { setTrackingSetId(''); } };
  const chooseCollectrCsv = async () => {
    if (importLock.current) return; importLock.current = true; setPreview(null); setCsvText(''); setImportName(''); setImportWorking(true); setImportMessage('');
    try { const picked = await File.pickFileAsync({ multipleFiles: false, mimeTypes: ['text/csv', 'text/plain', 'application/vnd.ms-excel'] }); if (picked.canceled) return; const file = picked.result; if (file.size > 2_000_000) throw new Error('That CSV is larger than FateDrop’s 2 MB safe import limit.'); const text = await file.text(); const next = await previewCollectrCsv(text); setCsvText(text); setImportName(file.name || 'Collectr export.csv'); setPreview(next); setImportMessage('Preview ready. Exact rows can be confirmed; ambiguous or unresolved rows remain held.'); } catch (caught) { setImportMessage(importError(caught)); } finally { importLock.current = false; setImportWorking(false); }
  };
  const confirmImport = async () => {
    if (importLock.current || !preview || !csvText || preview.preview.scale?.mayBeTruncated || !(preview.confirmationToken || preview.preview.confirmationToken)) return; importLock.current = true; setImportWorking(true); setImportMessage('');
    try { const result = await confirmCollectrCsv(csvText, preview.confirmationToken || preview.preview.confirmationToken || ''); setImportMessage(result.duplicate ? 'This exact export was already applied. Nothing was duplicated.' : `Import complete · ${result.summary.created} added · ${result.summary.updated} updated · ${result.summary.held} held.`); setPreview(null); setCsvText(''); setImportName(''); await load(); } catch (caught) { setImportMessage(importError(caught)); } finally { importLock.current = false; setImportWorking(false); }
  };

  return <CollectionsScreen><FlatList
    data={listRows} keyExtractor={(row) => row.kind === 'binder' ? `binder:${row.binder.setId}` : `set:${row.set.id}`}
    renderItem={({ item }) => item.kind === 'binder' ? <BinderRow binder={item.binder} /> : <CatalogueSetRow set={item.set} binder={binderBySet.get(item.set.id)} working={trackingSetId === item.set.id} onStart={() => void trackSet(item.set)} />}
    initialNumToRender={12} maxToRenderPerBatch={10} windowSize={7} keyboardShouldPersistTaps="handled" contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}
    refreshControl={<RefreshControl refreshing={loading} onRefresh={() => void load()} tintColor={FateDropColors.goldBright} />}
    ListHeaderComponent={<>
      <View style={styles.headerRow}><Pressable accessibilityRole="button" accessibilityLabel="Back to Fate Collections" onPress={() => router.canGoBack() ? router.back() : router.replace('/collections')} style={styles.back}><Ionicons name="chevron-back" size={20} color={FateDropColors.ivory} /></Pressable><View style={styles.flex}><Text style={styles.eyebrow}>FATE COLLECTIONS · BINDERS</Text><Text style={styles.title}>Finish the sets that matter to you.</Text><Text style={styles.copy}>See progress immediately, make missing cards impossible to miss, and open a verified checklist without mixing graded slabs into binder completion.</Text></View></View>
      <View style={styles.scopeRail}><ScopeButton label="MY BINDERS" selected={scope === 'mine'} onPress={() => { setScope('mine'); setQuery(''); }} /><ScopeButton label="ALL SETS" selected={scope === 'all-sets'} onPress={() => { setScope('all-sets'); setQuery(''); }} /></View>
      {scope === 'mine' ? <View style={styles.summary}><SummaryMetric icon="albums-outline" value={String(allBinders.length)} label="TRACKED" /><SummaryMetric icon="checkmark-done-outline" value={String(completed.length)} label="COMPLETE" /><SummaryMetric icon="ellipse-outline" value={String(inProgress.length)} label="BUILDING" /></View> : <View style={styles.allSetsIntro}><FateCollectionsArt kind="binders" size={68} /><View style={styles.flex}><Text style={styles.smallEyebrow}>VERIFIED SET LIBRARY</Text><Text style={styles.introTitle}>Start at 0%. Build from truth.</Text><Text style={styles.introCopy}>A binder can exist before you own a card. Ownership only changes when exact raw cards are added.</Text></View></View>}
      {loading && !data ? <StateLine icon="time-outline" text="Opening your binders…" loading /> : null}{error ? <StateLine icon="alert-circle-outline" text={error} danger /> : null}

      {scope === 'mine' && closest ? <>
        <FateSectionHeading eyebrow="NEXT COMPLETION" title="Closest set" copy="The binder with the clearest path to completion, using verified checklist progress only." />
        <Pressable accessibilityRole="button" onPress={() => router.push({ pathname: '/binder/[setId]', params: { setId: closest.setId, setName: closest.setName || undefined } })} style={({ pressed }) => [styles.closestCard, pressed && styles.pressed]}>
          <View style={styles.closestTop}><FateProgressRing value={closest.completionPercent} size={96} /><View style={styles.closestMain}><Text style={styles.closestEyebrow}>CLOSEST TO COMPLETION</Text><Text style={styles.closestName}>{closest.setName || 'Verified set'}</Text><Text style={styles.closestOwned}>{closest.ownedCount ?? '—'} / {closest.totalCount ?? '—'} cards owned</Text><View style={styles.closestFacts}><Text style={styles.missingFact}><Text style={styles.missingStrong}>{closest.missingCount ?? '—'}</Text> missing</Text><Text style={styles.valueFact}>{money(closest.value?.missingValue, currency)} verified missing value</Text></View></View><Ionicons name="chevron-forward" size={18} color={FateDropColors.goldBright} /></View>
          <View style={styles.track}><View style={[styles.fill, { width: `${Math.min(100, Math.max(0, closest.completionPercent || 0))}%` }]} /></View>
          <View style={styles.topNeeded}><Text style={styles.topNeededEyebrow}>NEXT CARDS TO FIND</Text><View style={styles.topNeededRow}>{topNeeded.length ? topNeeded.map((card) => <View key={card.fateCardId} style={styles.neededMini}><View style={styles.neededFlag}><Text style={styles.neededFlagText}>NEEDED</Text></View><View style={styles.flex}><Text style={styles.neededName} numberOfLines={1}>{card.name || 'Verified card'}</Text><Text style={styles.neededMeta}>#{card.collectorNumber || '—'} · exact printing</Text></View></View>) : <Text style={styles.noNeeded}>No verified missing-card detail yet.</Text>}</View></View>
        </Pressable>
      </> : null}

      {scope === 'mine' ? <ImportPanel preview={preview} importWorking={importWorking} importName={importName} importMessage={importMessage} onChoose={() => void chooseCollectrCsv()} onConfirm={() => void confirmImport()} /> : null}
      <FateSectionHeading eyebrow={scope === 'mine' ? 'YOUR BINDERS' : 'SET LIBRARY'} title={scope === 'mine' ? 'All tracked sets' : 'Start another binder'} copy={scope === 'mine' ? 'Filter by progress, then open a binder to see exactly what is needed.' : 'Search every verified set. Starting one does not invent ownership.'} />
      <View style={styles.searchBox}><Ionicons name="search-outline" size={18} color={FateDropColors.secondary} /><TextInput accessibilityLabel={scope === 'mine' ? 'Search binders' : 'Search all sets'} value={query} onChangeText={setQuery} placeholder={scope === 'mine' ? 'Search your binders…' : 'Search every verified set…'} placeholderTextColor={FateDropColors.secondary} style={styles.searchInput} autoCorrect={false} /></View>
      {scope === 'mine' ? <View style={styles.filterRail}><FilterButton label="All" selected={filter === 'all'} onPress={() => setFilter('all')} /><FilterButton label="In progress" selected={filter === 'progress'} onPress={() => setFilter('progress')} /><FilterButton label="Completed" selected={filter === 'complete'} onPress={() => setFilter('complete')} /></View> : <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.tcgRail}><FilterPill label="All games" selected={tcgFilter === 'all'} onPress={() => setTcgFilter('all')} /><FilterPill label="Pokémon" selected={tcgFilter === 'pokemon'} onPress={() => setTcgFilter('pokemon')} /><FilterPill label="One Piece" selected={tcgFilter === 'one-piece'} onPress={() => setTcgFilter('one-piece')} /></ScrollView>}
      <View style={styles.listHeader}><Text style={styles.listCopy}>{scope === 'mine' ? `${visible.length} binder${visible.length === 1 ? '' : 's'}` : `${availableSets.length} verified sets`}</Text>{scope === 'mine' ? <Pressable onPress={() => setSort(sort === 'progress' ? 'name' : 'progress')} style={styles.sortPill}><Text style={styles.sortText}>Sort: {sort === 'progress' ? 'Progress' : 'Name'}</Text><Ionicons name="swap-vertical" size={14} color={FateDropColors.secondary} /></Pressable> : null}</View>
    </>}
    ListFooterComponent={<><View>{!loading && !error && !listRows.length ? <StateLine icon="search-outline" text={query.trim() ? 'No sets match that search.' : scope === 'mine' ? 'No binders match this filter.' : 'The verified set catalogue is still building.'} /> : null}</View><View style={styles.truth}><Ionicons name="shield-checkmark-outline" size={16} color={FateDropColors.goldBright} /><Text style={styles.truthText}>One verified raw printing fills one binder slot. Duplicates increase quantity and value, not completion. Graded slabs remain separate.</Text></View></>}
  /></CollectionsScreen>;
}

function ImportPanel({ preview, importWorking, importName, importMessage, onChoose, onConfirm }: { preview: CollectrPreview | null; importWorking: boolean; importName: string; importMessage: string; onChoose: () => void; onConfirm: () => void }) { return <View style={styles.importPanel}><View style={styles.importHead}><View style={styles.flex}><Text style={styles.smallEyebrow}>COLLECTR IMPORT</Text><Text style={styles.importTitle}>Preview before anything changes.</Text><Text style={styles.importCopy}>Exact rows can update raw-card ownership. Ambiguous and unresolved rows stay held.</Text></View>{importWorking ? <ActivityIndicator size="small" color={FateDropColors.goldBright} /> : null}</View><Pressable disabled={importWorking} onPress={onChoose} style={styles.importButton}><Ionicons name="document-attach-outline" size={18} color={FateDropColors.goldBright} /><View style={styles.flex}><Text style={styles.importButtonTitle}>{importName || 'CHOOSE COLLECTR CSV'}</Text><Text style={styles.importButtonCopy}>{importName ? 'Choose a different export' : 'Preview only · 2 MB maximum'}</Text></View><Ionicons name="chevron-forward" size={15} color={FateDropColors.ivory} /></Pressable>{preview ? <View style={styles.previewCard}><View style={styles.previewTop}><Text style={styles.previewTitle}>SAFE IMPORT PREVIEW</Text><Text style={styles.previewCount}>{preview.preview.matched.exact} exact</Text></View><Text style={styles.previewCopy}>{preview.preview.plan.create} add · {preview.preview.plan.update} update · {preview.preview.plan.hold} held · {preview.preview.matched.ambiguous} ambiguous · {preview.preview.matched.unresolved} unresolved.</Text>{preview.preview.scale?.mayBeTruncated ? <Text style={styles.previewWarning}>This preview is incomplete. Choose a smaller export before confirming.</Text> : null}<Pressable disabled={importWorking || preview.preview.scale?.mayBeTruncated === true || !(preview.confirmationToken || preview.preview.confirmationToken)} onPress={onConfirm} style={styles.confirmButton}>{importWorking ? <ActivityIndicator size="small" color={FateDropColors.background} /> : <Ionicons name="checkmark-circle-outline" size={16} color={FateDropColors.background} />}<Text style={styles.confirmText}>CONFIRM EXACT IMPORT</Text></Pressable></View> : null}{importMessage ? <View style={styles.messageRow}><Ionicons name="information-circle-outline" size={15} color={FateDropColors.goldBright} /><Text style={styles.messageText}>{importMessage}</Text></View> : null}</View>; }
function SummaryMetric({ icon, value, label }: { icon: keyof typeof Ionicons.glyphMap; value: string; label: string }) { return <View style={styles.summaryMetric}><Ionicons name={icon} size={16} color={FateDropColors.goldBright} /><Text style={styles.summaryValue}>{value}</Text><Text style={styles.summaryLabel}>{label}</Text></View>; }
function ScopeButton({ label, selected, onPress }: { label: string; selected: boolean; onPress: () => void }) { return <Pressable onPress={onPress} style={[styles.scopeButton, selected && styles.scopeButtonActive]}><Text style={[styles.scopeText, selected && styles.scopeTextActive]}>{label}</Text>{selected ? <View style={styles.scopeGem} /> : null}</Pressable>; }
function FilterButton({ label, selected, onPress }: { label: string; selected: boolean; onPress: () => void }) { return <Pressable onPress={onPress} style={[styles.filterButton, selected && styles.filterButtonActive]}><Text style={[styles.filterText, selected && styles.filterTextActive]}>{label}</Text></Pressable>; }
function FilterPill({ label, selected, onPress }: { label: string; selected: boolean; onPress: () => void }) { return <Pressable onPress={onPress} style={[styles.filterPill, selected && styles.filterPillActive]}><Text style={[styles.filterPillText, selected && styles.filterPillTextActive]}>{label}</Text></Pressable>; }
function BinderRow({ binder }: { binder: FateCollectorSetBinder }) { return <Pressable onPress={() => router.push({ pathname: '/binder/[setId]', params: { setId: binder.setId, setName: binder.setName || undefined } })} style={({ pressed }) => [styles.binderRow, pressed && styles.pressed]}><FateProgressRing value={binder.status === 'available' ? binder.completionPercent : null} size={66} label="SET" /><View style={styles.binderText}><Text style={styles.binderName} numberOfLines={1}>{binder.setName || 'Verified set'}</Text><Text style={styles.binderMeta}>{binder.status === 'available' ? `${binder.ownedCount ?? '—'} / ${binder.totalCount ?? '—'} owned · ${binder.missingCount ?? '—'} missing` : 'Checklist building · owned cards kept'}</Text><View style={styles.rowTrack}><View style={[styles.rowFill, { width: `${Math.min(100, Math.max(0, binder.completionPercent || 0))}%` }]} /></View></View><Ionicons name="chevron-forward" size={16} color={FateDropColors.ivory} /></Pressable>; }
function CatalogueSetRow({ binder, onStart, set, working }: { binder?: FateCollectorSetBinder; onStart: () => void; set: FatePriceSet; working: boolean }) { const total = set.total ?? set.printedTotal; const open = () => router.push({ pathname: '/binder/[setId]', params: { setId: set.id, setName: set.name } }); return <View style={styles.catalogueRow}><View style={styles.catalogueIcon}><Ionicons name="albums-outline" size={22} color={FateDropColors.goldBright} /></View><Pressable disabled={!binder} onPress={open} style={styles.catalogueBody}><Text style={styles.catalogueName} numberOfLines={1}>{set.name}</Text><Text style={styles.catalogueMeta}>{set.seriesName || 'Verified series'} · {total ? `${total} cards` : 'checklist building'}</Text><Text style={[styles.catalogueStatus, binder && styles.catalogueStatusTracked]}>{binder ? `${pct(binder.completionPercent)} · ${binder.ownedCount || 0} owned` : 'NOT STARTED · 0 OWNED'}</Text></Pressable>{binder ? <Pressable onPress={open} style={styles.openSetButton}><Text style={styles.openSetText}>OPEN</Text><Ionicons name="chevron-forward" size={13} color={FateDropColors.ivory} /></Pressable> : <Pressable disabled={working} onPress={onStart} style={styles.startSetButton}>{working ? <ActivityIndicator size="small" color={FateDropColors.background} /> : <><Ionicons name="add" size={14} color={FateDropColors.background} /><Text style={styles.startSetText}>START</Text></>}</Pressable>}</View>; }
function StateLine({ danger = false, icon, loading = false, text }: { danger?: boolean; icon: keyof typeof Ionicons.glyphMap; loading?: boolean; text: string }) { return <View style={styles.stateLine}>{loading ? <ActivityIndicator size="small" color={FateDropColors.goldBright} /> : <Ionicons name={icon} size={18} color={danger ? FateDropColors.vanished : FateDropColors.muted} />}<Text style={styles.stateText}>{text}</Text></View>; }

const styles = StyleSheet.create({
  content: { width: '100%', maxWidth: 960, alignSelf: 'center', paddingHorizontal: 18, paddingBottom: 140 }, flex: { flex: 1 }, pressed: { opacity: .72 }, headerRow: { flexDirection: 'row', alignItems: 'flex-start', gap: 10, paddingTop: 8 }, back: { width: 44, height: 44, borderRadius: 16, borderWidth: 1, borderColor: FateDropColors.borderSoft, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(4,8,18,.58)' }, eyebrow: { color: FateDropColors.goldBright, fontSize: 10, fontWeight: '900', letterSpacing: 1.15 }, title: { color: FateDropColors.ivory, fontFamily: Fonts.serif, fontSize: 31, lineHeight: 36, marginTop: 5 }, copy: { color: FateDropColors.secondary, fontSize: 10.5, lineHeight: 16, marginTop: 6 },
  scopeRail: { flexDirection: 'row', minHeight: 52, marginTop: 16, borderWidth: 1, borderColor: 'rgba(226,197,141,.28)', borderRadius: 16, overflow: 'hidden', backgroundColor: 'rgba(3,7,18,.68)' }, scopeButton: { flex: 1, position: 'relative', alignItems: 'center', justifyContent: 'center' }, scopeButtonActive: { backgroundColor: `${FateDropColors.violetLight}12` }, scopeText: { color: FateDropColors.secondary, fontSize: 10, fontWeight: '900', letterSpacing: .6 }, scopeTextActive: { color: FateDropColors.ivory }, scopeGem: { position: 'absolute', bottom: 0, width: 24, height: 2, backgroundColor: FateDropColors.goldBright },
  summary: { flexDirection: 'row', marginTop: 12, borderRadius: 16, borderWidth: 1, borderColor: 'rgba(226,197,141,.20)', overflow: 'hidden', backgroundColor: 'rgba(4,8,21,.62)' }, summaryMetric: { flex: 1, alignItems: 'center', paddingVertical: 11, borderRightWidth: StyleSheet.hairlineWidth, borderRightColor: FateDropColors.border }, summaryValue: { color: FateDropColors.ivory, fontFamily: Fonts.serif, fontSize: 18, marginTop: 3 }, summaryLabel: { color: FateDropColors.muted, fontSize: 7, fontWeight: '900', letterSpacing: .65, marginTop: 2 }, allSetsIntro: { flexDirection: 'row', alignItems: 'center', gap: 9, marginTop: 13, padding: 12, borderWidth: 1, borderColor: 'rgba(226,197,141,.28)', borderRadius: 16, backgroundColor: 'rgba(4,8,21,.72)' }, smallEyebrow: { color: FateDropColors.goldBright, fontSize: 8, fontWeight: '900', letterSpacing: .9 }, introTitle: { color: FateDropColors.ivory, fontFamily: Fonts.serif, fontSize: 18, marginTop: 3 }, introCopy: { color: FateDropColors.secondary, fontSize: 9.5, lineHeight: 14, marginTop: 4 },
  closestCard: { padding: 14, borderWidth: 1, borderColor: 'rgba(226,197,141,.50)', borderRadius: 20, backgroundColor: 'rgba(5,9,20,.86)', overflow: 'hidden' }, closestTop: { flexDirection: 'row', alignItems: 'center', gap: 12 }, closestMain: { flex: 1 }, closestEyebrow: { color: FateDropColors.goldBright, fontSize: 7.5, fontWeight: '900', letterSpacing: 1 }, closestName: { color: FateDropColors.ivory, fontFamily: Fonts.serif, fontSize: 20, lineHeight: 24, marginTop: 4 }, closestOwned: { color: FateDropColors.secondary, fontSize: 10, marginTop: 3 }, closestFacts: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 8 }, missingFact: { color: FateDropColors.secondary, fontSize: 9 }, missingStrong: { color: FateDropColors.echo, fontWeight: '900' }, valueFact: { color: FateDropColors.secondary, fontSize: 9 }, track: { height: 4, borderRadius: 2, backgroundColor: 'rgba(255,255,255,.09)', marginTop: 13, overflow: 'hidden' }, fill: { height: 4, borderRadius: 2, backgroundColor: FateDropColors.goldBright }, topNeeded: { borderTopWidth: 1, borderColor: 'rgba(226,197,141,.16)', marginTop: 12, paddingTop: 10 }, topNeededEyebrow: { color: FateDropColors.goldBright, fontSize: 7.5, fontWeight: '900', letterSpacing: .9 }, topNeededRow: { gap: 6, marginTop: 7 }, neededMini: { flexDirection: 'row', alignItems: 'center', gap: 8, padding: 8, borderRadius: 11, borderWidth: 1, borderColor: `${FateDropColors.echo}2C`, backgroundColor: `${FateDropColors.echo}07` }, neededFlag: { paddingHorizontal: 6, paddingVertical: 4, borderRadius: 7, backgroundColor: `${FateDropColors.echo}16`, borderWidth: 1, borderColor: `${FateDropColors.echo}3A` }, neededFlagText: { color: FateDropColors.echo, fontSize: 6.3, fontWeight: '900', letterSpacing: .55 }, neededName: { color: FateDropColors.ivory, fontSize: 10.5, fontWeight: '900' }, neededMeta: { color: FateDropColors.muted, fontSize: 8, marginTop: 2 }, noNeeded: { color: FateDropColors.secondary, fontSize: 10 },
  importPanel: { marginTop: 16, padding: 13, borderWidth: 1, borderColor: 'rgba(226,197,141,.28)', borderRadius: 17, backgroundColor: 'rgba(4,8,21,.72)' }, importHead: { flexDirection: 'row', gap: 9 }, importTitle: { color: FateDropColors.ivory, fontFamily: Fonts.serif, fontSize: 17, marginTop: 3 }, importCopy: { color: FateDropColors.secondary, fontSize: 9.5, lineHeight: 14, marginTop: 4 }, importButton: { minHeight: 54, flexDirection: 'row', alignItems: 'center', gap: 8, marginTop: 10, paddingHorizontal: 11, borderRadius: 12, borderWidth: 1, borderColor: 'rgba(226,197,141,.30)', backgroundColor: `${FateDropColors.goldBright}06` }, importButtonTitle: { color: FateDropColors.goldBright, fontSize: 9, fontWeight: '900' }, importButtonCopy: { color: FateDropColors.secondary, fontSize: 8, marginTop: 2 }, previewCard: { marginTop: 9, padding: 10, borderWidth: 1, borderColor: `${FateDropColors.violetLight}38`, borderRadius: 12, backgroundColor: 'rgba(3,7,18,.62)' }, previewTop: { flexDirection: 'row', justifyContent: 'space-between' }, previewTitle: { color: FateDropColors.goldBright, fontSize: 8, fontWeight: '900' }, previewCount: { color: FateDropColors.ivory, fontSize: 11, fontWeight: '900' }, previewCopy: { color: FateDropColors.secondary, fontSize: 9, lineHeight: 14, marginTop: 5 }, previewWarning: { color: FateDropColors.vanished, fontSize: 9, marginTop: 5 }, confirmButton: { minHeight: 41, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6, marginTop: 9, borderRadius: 10, backgroundColor: FateDropColors.goldBright }, confirmText: { color: FateDropColors.background, fontSize: 8, fontWeight: '900' }, messageRow: { flexDirection: 'row', gap: 6, marginTop: 8 }, messageText: { flex: 1, color: FateDropColors.secondary, fontSize: 9, lineHeight: 14 },
  searchBox: { minHeight: 49, flexDirection: 'row', alignItems: 'center', gap: 8, paddingHorizontal: 12, borderWidth: 1, borderColor: 'rgba(226,197,141,.28)', borderRadius: 13, backgroundColor: 'rgba(4,8,21,.82)' }, searchInput: { flex: 1, color: FateDropColors.ivory, fontSize: 12 }, filterRail: { flexDirection: 'row', marginTop: 10, borderRadius: 14, borderWidth: 1, borderColor: FateDropColors.border, overflow: 'hidden' }, filterButton: { flex: 1, minHeight: 39, alignItems: 'center', justifyContent: 'center' }, filterButtonActive: { backgroundColor: `${FateDropColors.goldBright}0D` }, filterText: { color: FateDropColors.secondary, fontSize: 9 }, filterTextActive: { color: FateDropColors.goldBright, fontWeight: '900' }, tcgRail: { gap: 7, marginTop: 10 }, filterPill: { paddingHorizontal: 12, paddingVertical: 8, borderRadius: 999, borderWidth: 1, borderColor: FateDropColors.border, backgroundColor: FateDropColors.glass }, filterPillActive: { borderColor: FateDropColors.goldBright, backgroundColor: `${FateDropColors.goldBright}0D` }, filterPillText: { color: FateDropColors.secondary, fontSize: 9 }, filterPillTextActive: { color: FateDropColors.ivory, fontWeight: '900' }, listHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 11, marginBottom: 9 }, listCopy: { color: FateDropColors.secondary, fontSize: 9.5 }, sortPill: { flexDirection: 'row', alignItems: 'center', gap: 4, minHeight: 36 }, sortText: { color: FateDropColors.secondary, fontSize: 9 },
  binderRow: { minHeight: 84, flexDirection: 'row', alignItems: 'center', gap: 10, padding: 9, marginBottom: 9, borderWidth: 1, borderColor: 'rgba(226,197,141,.24)', borderRadius: 15, backgroundColor: 'rgba(4,8,21,.72)' }, binderText: { flex: 1 }, binderName: { color: FateDropColors.ivory, fontFamily: Fonts.serif, fontSize: 15 }, binderMeta: { color: FateDropColors.secondary, fontSize: 9, marginTop: 3 }, rowTrack: { height: 3, borderRadius: 2, overflow: 'hidden', backgroundColor: 'rgba(255,255,255,.08)', marginTop: 7 }, rowFill: { height: 3, backgroundColor: FateDropColors.goldBright }, catalogueRow: { minHeight: 78, flexDirection: 'row', alignItems: 'center', gap: 9, padding: 9, marginBottom: 9, borderWidth: 1, borderColor: 'rgba(226,197,141,.24)', borderRadius: 14, backgroundColor: 'rgba(4,8,21,.72)' }, catalogueIcon: { width: 44, height: 54, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: `${FateDropColors.violetLight}38`, borderRadius: 8, backgroundColor: `${FateDropColors.violetLight}08` }, catalogueBody: { flex: 1 }, catalogueName: { color: FateDropColors.ivory, fontFamily: Fonts.serif, fontSize: 14 }, catalogueMeta: { color: FateDropColors.secondary, fontSize: 8, marginTop: 3 }, catalogueStatus: { color: FateDropColors.muted, fontSize: 7, fontWeight: '900', marginTop: 5 }, catalogueStatusTracked: { color: FateDropColors.manifested }, startSetButton: { minWidth: 63, minHeight: 36, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 2, borderRadius: 10, backgroundColor: FateDropColors.goldBright }, startSetText: { color: FateDropColors.background, fontSize: 8, fontWeight: '900' }, openSetButton: { minWidth: 60, minHeight: 36, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: FateDropColors.border, borderRadius: 10 }, openSetText: { color: FateDropColors.ivory, fontSize: 8, fontWeight: '900' }, stateLine: { flexDirection: 'row', alignItems: 'center', gap: 9, padding: 14, marginTop: 10, borderRadius: 14, borderWidth: 1, borderColor: FateDropColors.border, backgroundColor: FateDropColors.glass }, stateText: { flex: 1, color: FateDropColors.secondary, fontSize: 10, lineHeight: 15 }, truth: { flexDirection: 'row', gap: 8, marginTop: 18, padding: 12, borderRadius: 14, borderWidth: 1, borderColor: 'rgba(226,197,141,.20)', backgroundColor: 'rgba(4,8,21,.62)' }, truthText: { flex: 1, color: FateDropColors.secondary, fontSize: 9, lineHeight: 14 },
});
